FROM node:18-alpine

WORKDIR /usr/src/app

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

COPY package*.json ./
RUN npm install

ARG PORT=80
ENV PORT $PORT
EXPOSE $PORT

RUN npm run build


CMD ["node", "-r", "dotenv/config", "dist/server.js"]
