version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env
